import {
  HandLandmarker,
  FilesetResolver,
} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14";

const WASM_URL =
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL_URL =
  "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta";
const GEMINI_MODEL = "gemini-omni-flash-preview";
const STYLES = {
  movie3d:
    "Transform the person into a 3D animated movie character (stylized CGI " +
    "animation look, expressive big eyes, soft lighting).",
  anime:
    "Redraw the video as a hand-drawn anime with clean line art, cel " +
    "shading, and vibrant colors.",
  clay: "Transform the scene into claymation stop-motion with visible clay texture.",
  watercolor:
    "Repaint the video as a soft watercolor painting with loose brushwork.",
};
const PROMPT_SUFFIX =
  " This is a strict pixel-aligned edit of the source video: keep the same " +
  "pose, motion, timing, clothing colors, and background. The camera must " +
  "not change — no zoom, no crop, no recentering, and no change to the " +
  "field of view. The person's face and body must stay at exactly the same " +
  "position and size in the frame as the source: eyes, nose, and mouth must " +
  "remain at the same screen coordinates in every frame. Match the facial " +
  "expression exactly, frame by frame: preserve the exact degree of mouth " +
  "openness at every moment — if the mouth is slightly open and still, keep " +
  "it slightly open and still; do not close it, and do not add talking or " +
  "any mouth movement that is not in the source. Mirror blinks, gaze " +
  "direction, and eyebrow position at the same moments as the source. " +
  "Change only the visual style, nothing about the geometry, composition, " +
  "or performance.";

const WRIST = 0, THUMB_TIP = 4, INDEX_TIP = 8, MIDDLE_MCP = 9;
const MIDDLE_TIP = 12, RING_TIP = 16, PINKY_TIP = 20;
// Tip -> PIP joint, for the finger-extension gate (thumb exempt).
const PIP_OF = { [INDEX_TIP]: 6, [MIDDLE_TIP]: 10, [RING_TIP]: 14, [PINKY_TIP]: 18 };

// Tracking constants — same audited pipeline as the live web app.
const MAX_LOST_FRAMES = 25;
const JUMP_CONFIRM_FRAMES = 2;

const orig = document.getElementById("orig");
const sty = document.getElementById("sty");
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");
const statusEl = document.getElementById("status");
const stage = document.getElementById("stage");
const drop = document.getElementById("drop");
const dropInside = document.getElementById("drop-inside");
const fileInput = document.getElementById("file");
const fileInside = document.getElementById("file-inside");
const mainBig = document.getElementById("main-big");
const insideBig = document.getElementById("inside-big");
const insideClear = document.getElementById("inside-clear");
const assignCard = document.getElementById("assign");
const assignRows = document.getElementById("assign-rows");
const panel = document.getElementById("panel");
const btnGenerate = document.getElementById("btn-generate");
const btnPlaceholder = document.getElementById("btn-placeholder");
const btnMulti = document.getElementById("btn-multi");
const btnPlay = document.getElementById("btn-play");
const btnExport = document.getElementById("btn-export");

let landmarker = null;
let videoFile = null;
let haveAI = false;        // stylized video generated by Gemini
let haveInside = false;    // user-supplied video pool shown inside the frames
let insideFiles = [];      // {name, video} — uploaded inside videos, in order
let assign = ["auto", "auto", "auto", "auto"]; // per band: pool index or "auto"
let usePlaceholder = false; // hue-shift stand-in for keyless testing
let trackers = []; // one QuadTracker per active finger band (set up below)
let recorder = null;
let exporting = false;

function status(msg) {
  statusEl.textContent = msg;
  // Messages ending in an ellipsis are in-progress — show the spinner.
  statusEl.classList.toggle("working", /…\s*$/.test(msg));
}

// ---- key + style panel ----
const keyInput = document.getElementById("gem-key");
const keyRemember = document.getElementById("gem-remember");
const styleSelect = document.getElementById("style-select");
const styleCustom = document.getElementById("style-custom");

keyInput.value =
  localStorage.getItem("gemini-key") || sessionStorage.getItem("gemini-key") || "";
keyRemember.checked = !!localStorage.getItem("gemini-key");
styleSelect.value = localStorage.getItem("ai-style") || "movie3d";
styleCustom.value = localStorage.getItem("ai-style-custom") || "";
styleCustom.classList.toggle("hidden", styleSelect.value !== "custom");
styleSelect.addEventListener("change", () => {
  styleCustom.classList.toggle("hidden", styleSelect.value !== "custom");
  localStorage.setItem("ai-style", styleSelect.value);
});
styleCustom.addEventListener("change", () =>
  localStorage.setItem("ai-style-custom", styleCustom.value)
);
function saveKey() {
  const key = keyInput.value.trim();
  localStorage.removeItem("gemini-key");
  sessionStorage.removeItem("gemini-key");
  if (key) (keyRemember.checked ? localStorage : sessionStorage).setItem("gemini-key", key);
  return key;
}
function prompt() {
  const style =
    styleSelect.value === "custom" && styleCustom.value.trim()
      ? styleCustom.value.trim()
      : STYLES[styleSelect.value] || STYLES.movie3d;
  return style + PROMPT_SUFFIX;
}

// ---- video loading ----
// Two-video mode: an uploaded inside video replaces the whole key & style
// step — the frame becomes a window into it, no generation involved.
function applyMode() {
  panel.classList.toggle("skipped", haveInside);
  btnGenerate.classList.toggle("hidden", haveInside);
  btnPlaceholder.classList.toggle("hidden", haveInside);
}

fileInput.addEventListener("change", (e) => loadFiles([...e.target.files]));
drop.addEventListener("dragover", (e) => {
  e.preventDefault();
  drop.classList.add("over");
});
drop.addEventListener("dragleave", () => drop.classList.remove("over"));
drop.addEventListener("drop", (e) => {
  e.preventDefault();
  drop.classList.remove("over");
  loadFiles([...e.dataTransfer.files]);
});

async function loadFiles(files) {
  if (files[0]) await loadVideo(files[0]);
  if (files.length > 1) await loadInsides(files.slice(1));
}

fileInside.addEventListener("change", (e) => loadInsides([...e.target.files]));
dropInside.addEventListener("dragover", (e) => {
  e.preventDefault();
  dropInside.classList.add("over");
});
dropInside.addEventListener("dragleave", () => dropInside.classList.remove("over"));
dropInside.addEventListener("drop", (e) => {
  e.preventDefault();
  dropInside.classList.remove("over");
  loadInsides([...e.dataTransfer.files]);
});

// Each upload ADDS to the pool; ✕ clears it. Assignment picks which pool
// video shows in which finger-gap window ("auto" cycles them in order).
async function loadInsides(files) {
  for (const file of files) {
    const v = document.createElement("video");
    v.playsInline = true;
    v.muted = true;
    v.src = URL.createObjectURL(file);
    await new Promise((res) => (v.onloadedmetadata = res));
    // Decode one frame so the window renders even before first play.
    await new Promise((res) => {
      v.onseeked = () => {
        v.onseeked = null;
        res();
      };
      v.currentTime = 0.01;
    });
    stage.appendChild(v); // stays hidden (stage videos are display:none)
    insideFiles.push({ name: file.name, video: v });
  }
  if (!insideFiles.length) return;
  haveInside = true;
  applyMode();
  renderAssign();
  insideBig.textContent =
    insideFiles.length === 1
      ? `✓ ${insideFiles[0].name}`
      : `✓ ${insideFiles.length} inside videos`;
  dropInside.classList.add("compact");
  insideClear.classList.remove("hidden");
  if (videoFile) {
    btnPlay.disabled = false;
    btnExport.disabled = false;
    status(
      insideFiles.length === 1
        ? "Both videos loaded — preview or export. No key or style needed."
        : `${insideFiles.length} inside videos loaded — assign them to windows below, then preview or export.`
    );
  }
}

insideClear.addEventListener("click", (e) => {
  e.preventDefault();
  e.stopPropagation();
  for (const f of insideFiles) {
    URL.revokeObjectURL(f.video.src);
    f.video.remove();
  }
  insideFiles = [];
  assign = ["auto", "auto", "auto", "auto"];
  haveInside = false;
  fileInside.value = "";
  applyMode();
  renderAssign();
  insideBig.textContent = "Drop inside video(s)";
  dropInside.classList.remove("compact");
  insideClear.classList.add("hidden");
  const ready = haveAI || usePlaceholder;
  btnPlay.disabled = !videoFile || !ready;
  btnExport.disabled = !videoFile || !ready;
  if (videoFile && !ready)
    status("Inside videos removed — generate an AI style or use the placeholder.");
});

// The pool video for band i, honoring an explicit assignment or cycling
// the pool in order ("auto").
function bandVideo(i) {
  if (!insideFiles.length) return null;
  const a = assign[i];
  const j = a === "auto" || +a >= insideFiles.length ? i % insideFiles.length : +a;
  return insideFiles[j].video;
}

function renderAssign() {
  const show =
    insideFiles.length >= 2 || (multiMode && insideFiles.length >= 1);
  assignCard.classList.toggle("hidden", !show);
  if (!show) return;
  const bands = multiMode ? MULTI_BANDS : [SINGLE_BAND];
  assignRows.innerHTML = "";
  bands.forEach((band, i) => {
    const row = document.createElement("div");
    row.className = "assign-row";
    const label = document.createElement("span");
    label.className = "w-name";
    label.textContent = band.name;
    const sel = document.createElement("select");
    const auto = document.createElement("option");
    auto.value = "auto";
    auto.textContent = `Auto — ${insideFiles[i % insideFiles.length].name}`;
    sel.appendChild(auto);
    insideFiles.forEach((f, j) => {
      const o = document.createElement("option");
      o.value = j;
      o.textContent = f.name;
      sel.appendChild(o);
    });
    sel.value =
      assign[i] === "auto" || +assign[i] >= insideFiles.length ? "auto" : assign[i];
    sel.addEventListener("change", () => (assign[i] = sel.value));
    row.append(label, sel);
    assignRows.appendChild(row);
  });
}

async function loadVideo(file) {
  videoFile = file;
  haveAI = false;
  usePlaceholder = false;
  btnPlay.disabled = !haveInside;
  btnExport.disabled = !haveInside;
  btnPlay.textContent = "▶ Preview";
  orig.src = URL.createObjectURL(file);
  await new Promise((res) => (orig.onloadedmetadata = res));
  canvas.width = orig.videoWidth;
  canvas.height = orig.videoHeight;
  stage.style.display = "flex";
  drop.classList.add("compact");
  mainBig.textContent = `✓ ${file.name}`;
  drawPoster();
  status(
    `Loaded ${file.name} (${orig.videoWidth}×${orig.videoHeight}, ` +
    `${orig.duration.toFixed(1)}s). ` +
    (haveInside
      ? "Both videos loaded — preview or export."
      : "Add an inside video, generate the AI video, or test with the placeholder.")
  );
  if (!landmarker) initLandmarker();
}

function drawPoster() {
  orig.currentTime = 0.01;
  orig.onseeked = () => {
    ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
    orig.onseeked = null;
  };
}

async function initLandmarker() {
  status("Loading hand tracker…");
  const fileset = await FilesetResolver.forVisionTasks(WASM_URL);
  landmarker = await HandLandmarker.createFromOptions(fileset, {
    baseOptions: { modelAssetPath: MODEL_URL, delegate: "GPU" },
    runningMode: "VIDEO",
    numHands: 2,
    minHandDetectionConfidence: 0.3,
    minHandPresenceConfidence: 0.3,
    minTrackingConfidence: 0.3,
  });
  status("Hand tracker ready.");
}

// Dev hook: render one frame at time t (seconds) without realtime playback —
// lets automated tests drive the pipeline in environments that suspend media.
window.__step = (t) =>
  new Promise((resolve) => {
    orig.onseeked = () => {
      orig.onseeked = null;
      if (!landmarker) return resolve(null); // tracker still loading
      ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
      const res = landmarker.detectForVideo(orig, performance.now());
      const hands = res.landmarks || [];
      for (const tk of trackers) tk.update(hands);
      trackers.forEach((tk, i) => {
        if (tk.visible) {
          drawWindow(tk.corners, tk.presence, bandWindowVideo(i));
          drawOutline(tk.corners, t, tk.presence);
        }
      });
      const primary = trackers[0];
      resolve({
        presence: +primary.presence.toFixed(2),
        corners: primary.corners
          ? primary.corners.map((p) => [Math.round(p.x), Math.round(p.y)])
          : null,
        // Band-aligned: quads[i] is band i's quad or null while invisible.
        quads: trackers.map((tk) =>
          tk.visible
            ? tk.corners.map((p) => [Math.round(p.x), Math.round(p.y)])
            : null
        ),
      });
    };
    orig.currentTime = t;
  });

// Dev convenience: ?src=file.mov loads a local file from the dev server;
// ?inside=file.mp4 does the same for the inside video.
const srcParam = new URLSearchParams(location.search).get("src");
if (srcParam) {
  fetch(srcParam)
    .then((r) => r.blob())
    .then((b) => loadVideo(new File([b], srcParam, { type: "video/quicktime" })));
}
const insideParams = new URLSearchParams(location.search).getAll("inside");
if (insideParams.length) {
  Promise.all(
    insideParams.map((s) =>
      fetch(s).then((r) => r.blob()).then((b) => new File([b], s, { type: "video/mp4" }))
    )
  ).then(loadInsides);
}

// ---- AI generation (Gemini Omni Flash video editing, BYOK) ----

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const fr = new FileReader();
    fr.onload = () => resolve(fr.result.split(",")[1]);
    fr.onerror = reject;
    fr.readAsDataURL(file);
  });
}

async function gemFetch(key, path, init = {}) {
  const res = await fetch(`${GEMINI_BASE}/${path}`, {
    ...init,
    headers: {
      "x-goog-api-key": key,
      ...(init.body ? { "Content-Type": "application/json" } : {}),
      ...(init.headers || {}),
    },
  });
  if (!res.ok) {
    let detail = res.statusText;
    try {
      detail = (await res.json())?.error?.message || detail;
    } catch {}
    throw new Error(`${res.status}: ${detail.slice(0, 160)}`);
  }
  return res.json();
}

// The Interactions API is in preview; be liberal about where the output
// video and status live in the response. Verified live shape: the video is
// in steps[].content[] on the step with type "model_output".
function findOutputVideo(inter) {
  if (inter.output_video) return inter.output_video;
  if (inter.outputVideo) return inter.outputVideo;
  const lists = [inter.outputs, inter.output, inter.content].filter(Array.isArray);
  for (const step of inter.steps || []) {
    if (Array.isArray(step.content)) lists.push(step.content);
  }
  for (const list of lists) {
    const v = list.find(
      (o) => o?.type?.includes?.("video") || o?.video || o?.mime_type?.startsWith?.("video")
    );
    if (v) return v.video || v;
  }
  return null;
}

function isPending(inter) {
  const s = (inter.status || inter.state || "").toLowerCase();
  return ["pending", "in_progress", "processing", "running", "queued"].some((k) =>
    s.includes(k)
  );
}

btnGenerate.addEventListener("click", async () => {
  const key = saveKey();
  if (!key) {
    status("Add your Gemini key above first (or use the placeholder).");
    keyInput.focus();
    return;
  }
  if (!videoFile) return;
  if (videoFile.size > 15 * 1024 * 1024) {
    status("⚠️ Keep the video under ~15MB (a few seconds of 720p) for inline upload.");
    return;
  }
  btnGenerate.disabled = true;
  try {
    status("Encoding video…");
    const b64 = await fileToBase64(videoFile);

    status("Submitting to Gemini Omni Flash — this can take a few minutes…");
    let inter = await gemFetch(key, "interactions", {
      method: "POST",
      body: JSON.stringify({
        model: GEMINI_MODEL,
        input: [
          {
            type: "video",
            mime_type: videoFile.type || "video/mp4",
            data: b64,
          },
          { type: "text", text: prompt() },
        ],
      }),
    });
    console.log("interaction response:", inter);

    // Poll the interaction until it settles, if it reports as in-progress.
    const id = inter.id || inter.name;
    let waited = 0;
    while (isPending(inter) && waited < 600) {
      await sleep(5000);
      waited += 5;
      inter = await gemFetch(key, `interactions/${id}`);
      status(`Generating… (${waited}s, status: ${inter.status || inter.state || "working"})`);
    }

    const vid = findOutputVideo(inter);
    if (!vid) {
      console.error("full response:", inter);
      throw new Error("no video in response — see console for the raw payload");
    }

    let blob;
    if (vid.data) {
      const bytes = Uint8Array.from(atob(vid.data), (c) => c.charCodeAt(0));
      blob = new Blob([bytes], { type: vid.mime_type || "video/mp4" });
    } else {
      // uri delivery: wait for the file to become ACTIVE, then download.
      let uri = vid.uri || vid.file_uri || vid.url;
      if (!uri) throw new Error("no video data or uri in response");
      const fileName = uri.includes("/files/")
        ? "files/" + uri.split("/files/")[1].split(/[?#]/)[0]
        : uri;
      if (!/^https?:/.test(uri)) uri = `${GEMINI_BASE}/${fileName}:download?alt=media`;
      for (let i = 0; i < 60; i++) {
        const f = await gemFetch(key, fileName);
        if ((f.state || "").includes("ACTIVE")) break;
        status(`Waiting for the output file… (${(f.state || "processing").toLowerCase()})`);
        await sleep(5000);
      }
      status("Downloading result…");
      const res = await fetch(uri, { headers: { "x-goog-api-key": key } });
      if (!res.ok) throw new Error(`download failed: ${res.status}`);
      blob = await res.blob();
    }

    sty.src = URL.createObjectURL(blob);
    await new Promise((res) => (sty.onloadedmetadata = res));
    haveAI = true;
    usePlaceholder = false;
    btnPlay.disabled = false;
    btnExport.disabled = false;
    status("AI video ready — preview or export.");
  } catch (err) {
    console.error(err);
    status("⚠️ Generation failed: " + (err.message || err));
  } finally {
    btnGenerate.disabled = false;
  }
});

btnPlaceholder.addEventListener("click", () => {
  if (!videoFile) return;
  usePlaceholder = true;
  haveAI = false;
  btnPlay.disabled = false;
  btnExport.disabled = false;
  status("Placeholder style active (hue shift) — preview or export, no key needed.");
});

// ---- tracking (ported from finger-frame-effect main.js) ----
function toPixel(lm) {
  return { x: lm.x * canvas.width, y: lm.y * canvas.height };
}
function dist(a, b) {
  return Math.hypot(a.x - b.x, a.y - b.y);
}
function lerpPt(a, b, t) {
  return { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t };
}
function polygonArea(pts) {
  let a = 0;
  for (let i = 0; i < pts.length; i++) {
    const p = pts[i], q = pts[(i + 1) % pts.length];
    a += p.x * q.y - q.x * p.y;
  }
  return Math.abs(a / 2);
}

function segsIntersect(a, b, c, d) {
  const cross = (o, p, q) => (p.x - o.x) * (q.y - o.y) - (p.y - o.y) * (q.x - o.x);
  const d1 = cross(c, d, a), d2 = cross(c, d, b);
  const d3 = cross(a, b, c), d4 = cross(a, b, d);
  return d1 > 0 !== d2 > 0 && d3 > 0 !== d4 > 0;
}

// A band is a pair of adjacent fingertips; both hands' pairs form the quad
// [A.hi, B.hi, B.lo, A.lo], each hand contributing one edge — the same
// construction as the original thumb–index frame. Spread/area gates are
// fractions of the hand scale (wrist→middle-MCP) and the canvas area;
// non-thumb gaps are anatomically far smaller when fully spread, so their
// thresholds sit much lower.
const SINGLE_BAND = {
  name: "Thumb–index", lo: THUMB_TIP, hi: INDEX_TIP,
  acquire: 0.75, keep: 0.2, areaAcquire: 0.005, areaKeep: 0.0005,
};
const MULTI_BANDS = [
  SINGLE_BAND,
  { name: "Index–middle", lo: INDEX_TIP, hi: MIDDLE_TIP, acquire: 0.28, keep: 0.14, areaAcquire: 0.002, areaKeep: 0.001, hold: 10 },
  { name: "Middle–ring", lo: MIDDLE_TIP, hi: RING_TIP, acquire: 0.24, keep: 0.14, areaAcquire: 0.002, areaKeep: 0.001, hold: 10 },
  { name: "Ring–pinky", lo: RING_TIP, hi: PINKY_TIP, acquire: 0.26, keep: 0.14, areaAcquire: 0.002, areaKeep: 0.001, hold: 10 },
];

class QuadTracker {
  constructor(band) {
    this.band = band;
    this.hold = band.hold || MAX_LOST_FRAMES;
    this.reset();
  }

  reset() {
    this.corners = null;
    this.presence = 0;
    this.frameActive = false;
    this.lostFrames = 0;
    this.jumpFrames = 0;
  }

  get visible() {
    return !!this.corners && this.presence > 0.01;
  }

  computeQuad(hands) {
    if (hands.length !== 2) return null;
    const info = [];
    for (const lm of hands) {
      const px = (i) => toPixel(lm[i]);
      // Both fingers must actually be extended (tip farther from the wrist
      // than its PIP joint) — curled fingers otherwise yield sliver quads.
      for (const tip of [this.band.lo, this.band.hi]) {
        const pip = PIP_OF[tip];
        if (pip && dist(px(WRIST), px(tip)) <= dist(px(WRIST), px(pip)) * 1.15)
          return null;
      }
      info.push({
        hi: px(this.band.hi),
        lo: px(this.band.lo),
        wristX: px(WRIST).x,
        scale: dist(px(WRIST), px(MIDDLE_MCP)) + 1,
      });
    }
    const needed = this.frameActive ? this.band.keep : this.band.acquire;
    for (const hd of info) {
      if (dist(hd.lo, hd.hi) < hd.scale * needed) return null;
    }
    info.sort((a, b) => a.wristX - b.wristX);
    const [A, B] = info;
    const pts = [A.hi, B.hi, B.lo, A.lo];
    const cx = pts.reduce((s, p) => s + p.x, 0) / 4;
    const cy = pts.reduce((s, p) => s + p.y, 0) / 4;
    const hull = [...pts].sort(
      (a, b) => Math.atan2(a.y - cy, a.x - cx) - Math.atan2(b.y - cy, b.x - cx)
    );
    const minArea = this.frameActive ? this.band.areaKeep : this.band.areaAcquire;
    if (polygonArea(hull) < canvas.width * canvas.height * minArea) return null;
    // A twisted quad (opposite edges crossing — hands rotated toward each
    // other, or crossed fingers) isn't a real frame; reject it outright.
    if (
      segsIntersect(pts[0], pts[1], pts[2], pts[3]) ||
      segsIntersect(pts[1], pts[2], pts[3], pts[0])
    )
      return null;
    return pts;
  }

  update(hands) {
    const target = this.computeQuad(hands);
    if (target) {
      if (!this.corners) {
        this.lostFrames = 0;
        this.frameActive = true;
        this.jumpFrames = 0;
        this.corners = target;
        this.presence = Math.min(1, this.presence + 0.12);
      } else {
        const moved =
          target.reduce((s, p, i) => s + dist(p, this.corners[i]), 0) / 4;
        if (moved > canvas.width * 0.3 && ++this.jumpFrames < JUMP_CONFIRM_FRAMES) {
          if (++this.lostFrames > this.hold)
            this.presence = Math.max(0, this.presence - 0.05);
        } else {
          this.lostFrames = 0;
          this.frameActive = true;
          this.jumpFrames = 0;
          const alpha = Math.min(0.85, Math.max(0.35, moved / (canvas.width * 0.05)));
          this.corners = this.corners.map((c, i) => lerpPt(c, target[i], alpha));
          this.presence = Math.min(1, this.presence + 0.12);
        }
      }
    } else if (this.corners && ++this.lostFrames <= this.hold) {
      this.presence = Math.min(1, this.presence + 0.12);
    } else {
      this.presence = Math.max(0, this.presence - 0.05);
      if (this.presence === 0) {
        this.corners = null;
        this.frameActive = false;
        this.jumpFrames = 0;
      }
    }
  }
}

let multiMode = localStorage.getItem("multi-windows") === "1";
function makeTrackers() {
  return (multiMode ? MULTI_BANDS : [SINGLE_BAND]).map((b) => new QuadTracker(b));
}
trackers = makeTrackers();

function renderMultiBtn() {
  btnMulti.textContent = `🖐 Multi windows: ${multiMode ? "on" : "off"}`;
  btnMulti.setAttribute("aria-pressed", multiMode);
}
btnMulti.addEventListener("click", () => {
  multiMode = !multiMode;
  localStorage.setItem("multi-windows", multiMode ? "1" : "0");
  trackers = makeTrackers();
  renderMultiBtn();
  renderAssign();
  status(
    multiMode
      ? "Multi windows on — every gap between spread fingers becomes a window."
      : "Multi windows off — thumb + index frame only."
  );
});
renderMultiBtn();

// ---- rendering ----
function quadPath(q) {
  ctx.beginPath();
  ctx.moveTo(q[0].x, q[0].y);
  for (let i = 1; i < 4; i++) ctx.lineTo(q[i].x, q[i].y);
  ctx.closePath();
}

// The video revealed inside band i's quad: its assigned inside video, else
// the Gemini-stylized one, else null (placeholder hue shift of the original).
function bandWindowVideo(i) {
  return haveInside ? bandVideo(i) : haveAI ? sty : null;
}

// Every distinct video currently shown in a window — for sync/play/pause.
function activeWindowVideos() {
  if (haveInside) return [...new Set(trackers.map((_, i) => bandVideo(i)))];
  return haveAI ? [sty] : [];
}

function drawWindow(q, presence, vid) {
  ctx.save();
  quadPath(q);
  ctx.clip();
  ctx.globalAlpha = presence;
  if (vid) {
    ctx.drawImage(vid, 0, 0, canvas.width, canvas.height);
  } else {
    ctx.filter = "hue-rotate(140deg) saturate(1.7) contrast(1.15)";
    ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
    ctx.filter = "none";
  }
  ctx.restore();
  ctx.globalAlpha = 1;
}

function drawOutline(q, t, presence) {
  const slim = multiMode ? 0.65 : 1; // lighter chrome when several windows tile
  ctx.save();
  ctx.globalAlpha = presence;
  quadPath(q);
  ctx.setLineDash([10 * slim, 8 * slim]);
  ctx.lineDashOffset = -t * 40;
  ctx.lineWidth = 2 * slim;
  ctx.strokeStyle = "rgba(255,255,255,0.95)";
  ctx.shadowColor = "rgba(0,0,0,0.5)";
  ctx.shadowBlur = 6;
  ctx.stroke();
  ctx.setLineDash([]);
  ctx.lineDashOffset = 0;
  ctx.shadowBlur = 0;
  q.forEach((p, i) => {
    const r = (7 + Math.sin(t * 3 + i * 1.5) * 1.5) * slim;
    const halo = (t * 0.8 + i * 0.25) % 1;
    ctx.beginPath();
    ctx.arc(p.x, p.y, r + halo * 14 * slim, 0, Math.PI * 2);
    ctx.strokeStyle = `rgba(255,255,255,${0.5 * (1 - halo) * presence})`;
    ctx.lineWidth = 2 * slim;
    ctx.stroke();
    ctx.beginPath();
    ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
    ctx.fillStyle = "#fff";
    ctx.fill();
    ctx.beginPath();
    ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
    ctx.strokeStyle = "rgba(0,0,0,0.25)";
    ctx.lineWidth = 1.5 * slim;
    ctx.stroke();
  });
  ctx.restore();
}

let lastVideoTime = -1;
function loop() {
  if (!orig.paused && !orig.ended) requestAnimationFrame(loop);

  ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);

  if (landmarker && orig.currentTime !== lastVideoTime) {
    lastVideoTime = orig.currentTime;
    const res = landmarker.detectForVideo(orig, performance.now());
    const hands = res.landmarks || [];
    for (const tk of trackers) tk.update(hands);
  }

  // Keep the window videos in step with the original (a shorter inside video
  // holds its last frame rather than seeking past the end forever).
  for (const win of activeWindowVideos()) {
    const target = Math.min(orig.currentTime, Math.max(0, (win.duration || 0) - 0.05));
    if (Math.abs(win.currentTime - target) > 0.15) win.currentTime = target;
  }

  trackers.forEach((tk, i) => {
    if (tk.visible) {
      drawWindow(tk.corners, tk.presence, bandWindowVideo(i));
      drawOutline(tk.corners, orig.currentTime, tk.presence);
    }
  });
}

async function playThrough() {
  for (const tk of trackers) tk.reset();
  orig.currentTime = 0;
  for (const win of activeWindowVideos()) {
    win.currentTime = 0;
    win.play();
  }
  await orig.play();
  requestAnimationFrame(loop);
}

async function togglePreview() {
  if (!orig.paused && !orig.ended) {
    orig.pause();
    activeWindowVideos().forEach((v) => v.pause());
    btnPlay.textContent = "▶ Resume";
    status("Paused — click again (or the video) to resume.");
  } else if (orig.currentTime > 0 && !orig.ended) {
    btnPlay.textContent = "⏸ Pause";
    status("Previewing…");
    activeWindowVideos().forEach((v) => v.play());
    await orig.play();
    requestAnimationFrame(loop);
  } else {
    btnPlay.textContent = "⏸ Pause";
    status("Previewing…");
    await playThrough();
  }
}

btnPlay.addEventListener("click", () => {
  if (exporting) return;
  togglePreview();
});

// Clicking the video itself pauses/resumes, like a normal player.
canvas.addEventListener("click", () => {
  if (exporting || btnPlay.disabled) return;
  togglePreview();
});

orig.addEventListener("ended", () => {
  if (!exporting) {
    btnPlay.textContent = "▶ Preview";
    status("Preview finished — play again or export.");
  }
});

// ---- export (canvas capture -> webm download) ----
btnExport.addEventListener("click", async () => {
  if (exporting) return;
  exporting = true;
  btnExport.disabled = true;
  btnPlay.disabled = true;
  status("Exporting — playing the video through once…");

  const stream = canvas.captureStream(30);
  // Prefer MP4 where the browser can record it (Safari, newer Chrome);
  // fall back to WebM elsewhere.
  const mime = [
    "video/mp4;codecs=avc1.42E01E",
    "video/mp4",
    "video/webm;codecs=vp9",
    "video/webm",
  ].find((m) => MediaRecorder.isTypeSupported(m)) || "video/webm";
  const isMp4 = mime.startsWith("video/mp4");
  recorder = new MediaRecorder(stream, {
    mimeType: mime,
    videoBitsPerSecond: 10_000_000,
  });
  const chunks = [];
  recorder.ondataavailable = (e) => e.data.size && chunks.push(e.data);
  recorder.onstop = () => {
    const ext = isMp4 ? "mp4" : "webm";
    const blob = new Blob(chunks, { type: isMp4 ? "video/mp4" : "video/webm" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `finger-frame-ai.${ext}`;
    a.click();
    status(
      `Exported finger-frame-ai.${ext}.` +
      (isMp4
        ? ""
        : " (This browser records WebM — convert with: ffmpeg -i finger-frame-ai.webm -c:v libx264 out.mp4)")
    );
    exporting = false;
    btnExport.disabled = false;
    btnPlay.disabled = false;
    btnPlay.textContent = "▶ Preview";
  };

  orig.onended = () => {
    orig.onended = null;
    recorder.stop();
  };
  recorder.start();
  await playThrough();
});
